Feature: Optimize Ipfs calls
aragon/sdk pull request #192
Opened 2023-03-28 12:39 UTC by josemarinas

## Description

Please include a summary of the change and be sure you follow the contributions rules we do provide [here](./CONTRIBUTIONS.md)

Task: [ID]()

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder of the package after the [UPCOMING] title and before the latest version.
- [ ] I have tested my code on the test network.

2023-03-28 13:30 UTC, brickpop commented on modules/client/src/client-common/modules/ipfs.ts
> +    });
Why don't we recycle this code in a single place in common? We already have it for GraphQL

2023-03-28 14:28 UTC, brickpop approved these changes

2023-03-29 08:41 UTC, mathewmeconry requested changes

2023-03-29 08:41 UTC, mathewmeconry commented on modules/client/test/integration/core-modules/ipfs.test.ts
> +      url: "https://httpstat.us/504?sleep=100"
no need for a fake url. Use the IPFS mock

2023-03-29 11:07 UTC, mathewmeconry approved these changes

2023-03-29 12:07 UTC, merged