Feature: Add getProtocolVersion function
aragon/sdk pull request #262
Opened 2023-07-26 15:19 UTC by josemarinas

## Description

Add `getProtopcolVersion` function

Task ID: [OS-629](https://aragonassociation.atlassian.net/browse/OS-629)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them when possible.
- [ ] I have updated the `CHANGELOG.md` file in the root folder of the package after the `[UPCOMING]` title and before the latest version.
- [ ] I have tested my code on the test network.

2023-07-28 09:27 UTC, Michael-A-Heuer commented on modules/client/src/internal/client/methods.ts
> +  public async getProtocolVersion(
I imagined this to be a general function that you can apply to all OSx contracts (as mentioned here: https://discord.com/channels/672466989217873929/1132983258347487315/1132983261115723857).

We added the `protocolVersion` number function in v1.3.0.
This means that all prior contracts must be `1.0.0`.

In my tests, I used this (which you might want to improve).
```ts
export async function getProtocolVersion(
  contract: Contract
): Promise<[number, number, number]> {
  let protocolVersion: [number, number, number];
  try {
    contract.interface.getFunction('protocolVersion');
    protocolVersion = await contract.protocolVersion();
  } catch (error) {
    if (error.code === errors.INVALID_ARGUMENT) {
      protocolVersion = [1, 0, 0];
    } else {
      throw error;
    }
  }
  return protocolVersion;
}
```

2023-07-28 09:28 UTC, Michael-A-Heuer requested changes
We should provide a generic function and maybe a specifc one for the DAO

2023-07-28 09:30 UTC, Michael-A-Heuer commented on modules/client/src/internal/client/methods.ts
> +    const daoInstance = DAO__factory.connect(daoAddress, signer);
Use the `IProtocolVersion__factory` here

2023-07-28 12:03 UTC, Michael-A-Heuer commented on modules/client/src/internal/client/methods.ts
> +      // ethers5 throws an cannot estimate gas limit which could mean a lot of things
Hmm, this is not optimal indeed

2023-07-28 12:05 UTC, Michael-A-Heuer commented on modules/client/test/integration/client/methods.test.ts
> +
We should add a test where `[1,0,0]` is returned.

2023-07-28 13:39 UTC, Michael-A-Heuer commented on modules/client/test/helpers/deploy-v1-contracts.ts
> +  // try {
Why this is commented out?

2023-07-28 13:41 UTC, Michael-A-Heuer approved these changes, later dismissed

2023-07-28 14:18 UTC, mathewmeconry submitted a review, later dismissed

2023-07-31 13:12 UTC, Michael-A-Heuer approved these changes

2023-07-31 13:13 UTC, merged