Feature: Add prepareUpdate
aragon/sdk pull request #274
Opened 2023-08-22 19:57 UTC by josemarinas

## Description

Please include a summary of the change and be sure you follow the contributions rules we do provide [here](./CONTRIBUTIONS.md)

Task ID: [OS-556]()

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them when possible.
- [x] I have updated the `CHANGELOG.md` file in the root folder of the package after the `[UPCOMING]` title and before the latest version.
- [x] I have tested my code on the test network.

[OS-556]: https://aragonassociation.atlassian.net/browse/OS-556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-08-23 10:18 UTC, Rekard0 submitted a review, later dismissed
LGTM!

2023-08-25 13:45 UTC, mathewmeconry requested changes

2023-08-25 13:45 UTC, mathewmeconry commented on modules/client-common/src/internal/graphql-queries/plugin.ts
> +}
please apply some formatting here

2023-08-25 13:45 UTC, mathewmeconry commented on modules/client/src/addresslistVoting/internal/constants.ts
> +export const UPDATE_ABI: { [build: number]: MetadataAbiInput[] } = {
this can be loaded from the plugin metadata stored on ipfs. So should this be a constant?

2023-08-25 13:45 UTC, mathewmeconry commented on modules/client/src/addresslistVoting/internal/constants.ts
> +// use abi from plugin metadata
same as above. This information is stored on ipfs in the plugin metadata

2023-08-25 13:45 UTC, mathewmeconry commented on modules/client/src/addresslistVoting/types.ts
> +  updateParams?: any;
couldn't we use `Object` or `any[]`. I assume by the name that it has to be either an object or an array

2023-08-25 13:45 UTC, mathewmeconry commented on modules/client/src/multisig/internal/constants.ts
> +// use abi from plugin metadata
same ipfs comment as in the previous plugin

2023-08-25 13:45 UTC, mathewmeconry commented on modules/client/src/multisig/types.ts
> +  updateParams?: any;
same comment as in the previous plugin

2023-08-25 13:45 UTC, mathewmeconry commented on modules/client/src/tokenVoting/internal/constants.ts
>  export const INSTALLATION_ABI: MetadataAbiInput[] = [
same comment as in the previous plugin

2023-08-25 13:45 UTC, mathewmeconry commented on modules/client/src/tokenVoting/types.ts
> +  updateParams?: any;
same comment as in the previous plugin

2023-08-25 13:45 UTC, mathewmeconry commented on modules/client/test/integration/client/methods.test.ts
> +        // deply a new build to be able to update
```suggestion
        // deploy a new build to be able to update
```

2023-08-25 13:45 UTC, mathewmeconry commented on modules/client/CHANGELOG.md
> +## [1.13.1-rc1]
```suggestion
- Add prepareUpdate fruntion to all clients

## [1.13.1-rc1]
```

2023-08-25 13:45 UTC, mathewmeconry commented on modules/client-common/src/utils.ts
> +export async function* prepareGenericUpdate(
move code from here and `prepareGenericUpdateEstimation()` that is duplicated into another utils function to reduce code duplication

2023-08-25 13:45 UTC, mathewmeconry commented on modules/client-common/CHANGELOG.md
> +### Added
can you clean up this file that it has some proper spacing. 
For example
```
## [UPCOMING]
### Added
- Add generic prepare update function
- Add generic prepare update estimation function

## 1.5.0-rc0
### Changed
-  Renamed `LIVE_CONTRACTS` properties
```

2023-08-25 13:45 UTC, mathewmeconry commented on modules/common/CHANGELOG.md
>  ### Added
same as in the previous changelog. Apply the same format to all the changelog files

2023-08-28 09:00 UTC, josemarinas commented on modules/client/src/addresslistVoting/internal/constants.ts
> +export const UPDATE_ABI: { [build: number]: MetadataAbiInput[] } = {
I thought once the split happens this will be imported from the buildMetadata specified in the contract, [for example](https://github.com/aragon/osx/blob/6aedf05f86af3f1ceca48e21aab7c0f0ca832fab/packages/contracts/src/plugins/governance/majority-voting/token/build-metadata.json#L92C9-L98C9) and not from ipfs. This also relates to [this ticket](https://aragonassociation.atlassian.net/browse/OS-486) for deleting this constants

2023-08-28 09:08 UTC, josemarinas commented on modules/client/src/addresslistVoting/types.ts
> +  updateParams?: any;
mmm, you are right, it should be an array

2023-09-15 12:36 UTC, mathewmeconry submitted a review, later dismissed

2023-09-20 11:35 UTC, Rekard0 approved these changes

2023-09-20 20:03 UTC, merged