F/OS-674 Update use provider for non signed tx
aragon/sdk pull request #277
Opened 2023-08-25 15:01 UTC by josemarinas

## Description

Please include a summary of the change and be sure you follow the contributions rules we do provide [here](./CONTRIBUTIONS.md)

Task ID: [OS-674](https://aragonassociation.atlassian.net/browse/OS-674)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them when possible.
- [x] I have updated the `CHANGELOG.md` file in the root folder of the package after the `[UPCOMING]` title and before the latest version.
- [x] I have tested my code on the test network.

[OS-674]: https://aragonassociation.atlassian.net/browse/OS-674?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-08-25 16:12 UTC, Michael-A-Heuer requested changes
Looks like some unrelated change accidentally went into your PR. Please remove it

2023-08-25 16:12 UTC, Michael-A-Heuer commented on modules/client/src/internal/constants.ts
> +export const DEPOSIT_ESTIMATION_ADDRESS = "0x8626f6940E2eb28930eFb4CeF49B2d1F2C9C1199"
What does this have to do with this PR?

2023-08-28 07:58 UTC, mathewmeconry requested changes

2023-08-28 07:58 UTC, mathewmeconry commented on modules/client/src/tokenVoting/internal/utils.ts
>   * This function isn not 100% accurate.
```suggestion
 * This function is not 100% accurate.
```

2023-08-28 09:49 UTC, mathewmeconry approved these changes

2023-08-29 09:51 UTC, Michael-A-Heuer approved these changes

2023-08-31 09:54 UTC, merged