Add: Support for base sepolia and arbitrum sepolia
aragon/sdk pull request #320
Opened 2024-01-11 16:04 UTC by josemarinas

## Description

Add support fro base sepolia and arbitrum sepolia

Task ID: [OS-810](https://aragonassociation.atlassian.net/browse/OS-810)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them when possible.
- [ ] I have updated the `CHANGELOG.md` file in the root folder of the package after the `[UPCOMING]` title and before the latest version.
- [ ] I have tested my code on the test network.

2024-01-11 16:14 UTC, mathewmeconry requested changes

2024-01-11 16:14 UTC, mathewmeconry commented on modules/client-common/src/constants.ts
> +  },
don't you also need to add `baseSepolia` to this list?

2024-01-11 16:43 UTC, Rekard0 approved these changes

2024-01-12 08:05 UTC, mathewmeconry approved these changes

2024-01-12 08:17 UTC, merged